const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/private/tmp/cube-brainiac-qa/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();for(const [width,height] of [[375,667],[390,844],[360,800]]){const c=await b.newContext({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:2});const p=await c.newPage();await p.goto('http://127.0.0.1:4173');await p.locator('#calibration-skip').click();
assert.equal(await p.locator('.stage-text').evaluateAll(es=>es.every(e=>getComputedStyle(e).display!=='none')),true);await p.locator('#stages').evaluate(e=>e.scrollLeft=e.scrollWidth);assert.ok(await p.locator('#stages').evaluate(e=>e.scrollLeft>0));assert.equal(await p.locator('[data-stage="6"]').isDisabled(),true);assert.equal(await p.locator('[data-stage="0"]').getAttribute('aria-current'),'step');
await p.locator('.coach-task').scrollIntoViewIfNeeded();assert.ok(await p.evaluate(()=>document.querySelector('.coach-task').getBoundingClientRect().bottom<=document.querySelector('.workspace').getBoundingClientRect().top));const answer=await p.evaluate(()=>lessons[0].correct);await p.locator(`[data-answer="${answer}"]`).tap();assert.ok(await p.evaluate(()=>document.querySelector('.coach-response').getBoundingClientRect().top>=document.querySelector('.workspace').getBoundingClientRect().bottom));await p.locator('#hint').tap();
await p.locator('.cube-space').scrollIntoViewIfNeeded();assert.equal(await p.locator('.scene').evaluate(e=>getComputedStyle(e).scale),'0.9');
for(const index of [22,19,20]){await p.locator(`[data-index="${index}"]`).tap();}
assert.equal(await p.evaluate(()=>state.phase),'explain');
await p.screenshot({path:`tests/mobile-evidence/${width}-learn.png`,fullPage:true});
if(process.argv.includes('painter')){await p.locator('#fix-mode').tap();assert.equal(await p.locator('#solve').isDisabled(),true);const sizes=await p.locator('[data-paint]').evaluateAll(els=>els.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert.equal(sizes.length,54);assert.ok(sizes.every(r=>r.w>=44&&r.h>=44));for(const face of 'URFDLB'){await p.locator(`[data-color="${face}"]`).tap();const indices=await p.locator(`[data-face="${face}"] [data-paint]:not(:disabled)`).evaluateAll(es=>es.map(e=>e.dataset.paint));for(const i of indices)await p.locator(`[data-paint="${i}"]`).tap()}assert.equal(await p.locator('[data-paint]:disabled').count(),6);assert.match(await p.locator('#painting-progress').textContent(),/54 of 54/);assert.equal(await p.locator('#solve').isDisabled(),false);assert.ok(await p.locator('#solve').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth));await p.screenshot({path:`tests/mobile-evidence/${width}-painter.png`,fullPage:true})}
await c.close()}await b.close();console.log('PASS mobile Learn task/cube/feedback order'+(process.argv.includes('painter')?' and all 54 painter targets with real palette/sticker taps':''));})().catch(e=>{console.error(e);process.exit(1)});
