// QA-only Playwright dependency lives outside the static app.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/private/tmp/cube-brainiac-qa/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch();const results=[];for(const [width,height] of [[375,667],[390,844],[360,800]]){const c=await b.newContext({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:2});const p=await c.newPage();await p.goto('http://127.0.0.1:4173');await p.locator('#calibration-skip').click();
// Long-list layout fixture only; final checklist exercises a real solver result.
await p.evaluate(()=>{state.layout='red-right';state.mode='fix';state.paint=new Cube().move('R U F L D B').asString();state.solution=Array(8).fill("B' D' L' F' U' R'").join(' ').split(' ');state.playback=true;fixCube=Cube.fromString(state.paint);render()});
assert.equal(await p.locator('#objective-action').isVisible(),false);assert.equal(await p.locator('#solution-next').isVisible(),true);
await p.evaluate(()=>view.reset());const contained=await p.evaluate(()=>{const box=document.querySelector('.cube-space').getBoundingClientRect();return [...document.querySelectorAll('.sticker')].every(e=>{const r=e.getBoundingClientRect();return r.top>=box.top&&r.bottom<=box.bottom&&r.left>=box.left&&r.right<=box.right})});assert.equal(contained,true,'Entire rendered cube fits its drawing region');
for(const fraction of [0,.5,1]){await p.locator('.playback-details').evaluate((el,f)=>el.scrollTop=f*(el.scrollHeight-el.clientHeight),fraction);const r=await p.evaluate(()=>{const rect=s=>document.querySelector(s).getBoundingClientRect().toJSON();return {width:innerWidth,height:innerHeight,touch:navigator.maxTouchPoints,pageHeight:document.documentElement.scrollHeight,pageWidth:document.documentElement.scrollWidth,header:rect('header'),objective:rect('.objective'),cube:rect('.cube-space'),next:rect('#solution-next'),back:rect('#solution-back'),replay:rect('#solution-replay'),details:rect('.playback-details'),footer:rect('footer'),scroll:document.querySelector('.playback-details').scrollTop}});assert.equal(r.width,width);assert.equal(r.height,height);assert.ok(r.touch>0);assert.equal(r.pageHeight,height);assert.equal(r.pageWidth,width);assert.ok(r.cube.top>=r.objective.bottom);for(const key of ['cube','next','back','replay'])assert.ok(r[key].top>=0&&r[key].bottom<=r.footer.top,`${key} is visible`);await p.screenshot({path:`tests/mobile-evidence/${width}-playback-${fraction}.png`});results.push(r)}await p.locator('[data-solution-index="47"]').scrollIntoViewIfNeeded();assert.ok(await p.locator('[data-solution-index="47"]').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('footer').getBoundingClientRect().top));await p.locator('#playback-status').scrollIntoViewIfNeeded();assert.ok(await p.locator('#playback-status').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('footer').getBoundingClientRect().top));
const sizes=await p.locator('[data-solution-index]').evaluateAll(els=>els.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert.ok(sizes.every(r=>r.w>=44&&r.h>=44));
await p.locator('[data-solution-index="24"]').click();await p.waitForFunction(()=>!animating&&state.step===25);await p.locator('[data-solution-index="47"]').focus();assert.equal(await p.locator('[data-solution-index="47"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');await p.waitForFunction(()=>!animating&&state.step===48);await p.locator('[data-solution-index="0"]').click();await p.waitForFunction(()=>!animating&&state.step===1);
await c.close()}const desktop=await b.newContext({viewport:{width:1363,height:936}});const dp=await desktop.newPage();await dp.goto('http://127.0.0.1:4173');await dp.locator('#calibration-skip').click();assert.ok(await dp.evaluate(()=>document.querySelector('.journey').getBoundingClientRect().right<=document.querySelector('.workspace').getBoundingClientRect().left&&document.querySelector('.workspace').getBoundingClientRect().right<=document.querySelector('.coach').getBoundingClientRect().left));await dp.screenshot({path:'tests/mobile-evidence/desktop-learn.png'});await desktop.close();await b.close();fs.writeFileSync('tests/mobile-evidence/layout.json',JSON.stringify(results,null,2));console.log('PASS: 3 genuine mobile contexts × beginning/middle/end; cube and controls unobscured; no page scroll or horizontal overflow.');})().catch(e=>{console.error(e);process.exit(1)});
